### PR TITLE
[wip] Windows support

### PR DESCRIPTION
**Pull request by mcollina**

### CODE REVIEW

**Comment by geek** [comment]
LGTM

**Comment by mcollina** [comment]
I'll wait unit I finish porting all the scripts, that would probably be early next week.

**Comment by mcdonnelldean** [comment]
@mcollina Have you anything left to push to this branch? If not I will reuse it to complete the windows work.

**Comment by mcollina** [comment]
please go ahead and do whatever you prefer :)

**Comment by mcdonnelldean** [comment]
@mcollina I'll finish off the ones missed as I go.

**Pull request merged**
